openapi: 3.0.0
info:
  title: Meilisearch Search Playground
  version: "1.0"
servers:
  - url: http://165.232.185.237:7700
paths:
  /indexes/mf_index/search:
    post:
      summary: Search Mutual Funds
      description: Query mutual fund data with filters and sorting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  example: equity
                filter:
                  type: string
                  example: asset_class = "Equity" AND sub_asset_class = "Mid Cap"
                sort:
                  type: array
                  items:
                    type: string
                  example: ["final_score:desc"]
                limit:
                  type: integer
                  example: 10
                offset:
                  type: integer
                  example: 0
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  hits:
                    type: array
                    items:
                      type: object
                  estimatedTotalHits:
                    type: integer
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
